version: '3'
services:
  identity-api:
    build:
      context: ./src/back/Identity
      args:
        CONFIGURATION: ${BACK_CONFIGURATION}
        DOTNET_SDK: ${DOTNET_SDK}
        DOTNET_RUNTIME: ${DOTNET_RUNTIME}
        CON_STRING_ID: server=identity-pg;port=5432;database=identity;user Id=${PG_ID_USER};password=${PG_ID_USER}
    ports:
      - "5000:8080"
    networks:
      - identity-pg-net
      - kafka-net
    depends_on:
      - identity-pg
      - kafka
  
  identity-front:
    build: 
      context: ./src/front/
      dockerfile: ./apps/identity/Dockerfile
      args:
        CONFIGURATION: ${FRONT_CONFIGURATION}
    ports:
      - "5001:80"
    depends_on:
      - identity-api

  identity-pg:
    container_name: postgres-identity
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_DB: "identity"
      POSTGRES_USER: ${PG_ID_USER}
      POSTGRES_PASSWORD: ${PG_ID_PASSWORD}
    volumes:
      - pg-identity-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - identity-pg-net

  pg-admin:
    container_name: pgadmin-admin
    image: dpage/pgadmin4:8.3
    environment:
      PGADMIN_DEFAULT_EMAIL: "default@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    ports:
      - "5002:80"
    networks:
      - identity-pg-net
    depends_on:
      - identity-pg

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6.1
    restart: always
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
    - kafka-data:/bitnami/kafka
    networks:
      - kafka-net

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "5003:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - kafka-net

networks:
  identity-pg-net:
    driver: bridge
  kafka-net:
    driver: bridge

volumes:
  pg-identity-data:
  pgadmin-data:
  kui-data:
  kafka-data: